/* 1. Да се намерят всички стандартни изключения от йерархията на java.io.IOException.*/
public class Exercise_01 {
/*	Direct Known Subclasses:
	ChangedCharSetException,CharacterCodingException,CharConversionException,ClosedChannelException
	EOFException,FileLockInterruptionException,FileNotFoundException,FilerException,FileSystemException
	HttpRetryException,IIOException,InterruptedByTimeoutException,InterruptedIOException,InvalidPropertiesFormatException
	JMXProviderException,JMXServerErrorException,MalformedURLException,ObjectStreamException,ProtocolException,RemoteException
	SaslException,SocketException,SSLException,SyncFailedException,UnknownHostException,UnknownServiceException
	UnsupportedDataTypeException,UnsupportedEncodingException,UserPrincipalNotFoundException,UTFDataFormatException,ZipException*/
}
